EXT-1436: upgrade Node.js to v18.16.0
storyblok/field-plugin pull request #135
Opened 2023-04-19 14:21 UTC by eunjae-lee

## What?

This PR upgrades Node.js version to v18.16.0.

v16 is meeting End of Life this September, so we could just move onto v18. It's not that our customers also have to use v18, because the library itself will be transpiled to somewhat backward compatible version via vite.

![Screenshot 2023-04-19 at 16 20 29](https://user-images.githubusercontent.com/499898/233104761-fd2d3d37-dc56-461b-b07d-1bc53dac92da.png)

## How to test

Nothing should change.

2023-04-20 09:20 UTC, eunjae-lee commented
![Screenshot 2023-04-20 at 11 19 38](https://user-images.githubusercontent.com/499898/233320687-2bb6ba23-b5af-4631-8f41-51541c574021.png)

We're already using `fill-rule` instead of `fillRule` here, but I don't know why vue-tsc is failing with that error message 🤔

2023-04-21 08:32 UTC, johannes-lindgren requested changes
Would it be possible to specify

```
"engines": {
    "node": ">=14.19.1"
  },
```

in `package.json`?

If we encounter some compatibility issues, we can increase that number.

2023-04-21 08:32 UTC, johannes-lindgren commented on .node-version
Most people probably use nvm, so they're not going to benefit from `.node-version`. Maybe it's possible to create a symlink `.nvmrc` so that both files exist with identical content?

2023-04-21 09:42 UTC, eunjae-lee commented on .node-version
I've renamed it to `.nvmrc`. Both Bibi and I use [asdf](https://github.com/asdf-vm/asdf-nodejs/) and it supports both. It's fine with this.

2023-04-21 10:05 UTC, eunjae-lee commented
> Would it be possible to specify
> 
> ```
> "engines": {
>     "node": ">=14.19.1"
>   },
> ```
> 

Actually that is needed for Node.js libraries, but `field-plugin` is for browser. All we need is browser compatibility and I guess vite's standard is pretty okay for the modern browsers. If they want to support legacy, then they could enable legacy mode of vite.

2023-04-21 11:10 UTC, johannes-lindgren commented on .node-version
Should the `.node-version` files in the templates also be renamed?

2023-04-21 13:05 UTC, eunjae-lee commented on .node-version
oh you're right. nice catch.

2023-04-21 13:34 UTC, johannes-lindgren approved these changes

2023-04-21 13:34 UTC, merged