EXT-1274: Renames Action and Data Types
storyblok/field-plugin pull request #150
Opened 2023-04-26 11:17 UTC by johannes-lindgren

## What?

Breaking change which renames the types in @storyblok/field-plugin:

- `PluginState` → `FieldPluginData`
- `PluginActions` → `FieldPluginActions`

## Why?

To be consistent with the naming of the `FieldPluginResponse` type, and the `FieldPluginResponse.data` and `FieldPluginResponse.actions` properties.

2023-04-26 15:12 UTC, eunjae-lee requested changes
Can you also revert the version changes here?

2023-04-27 08:15 UTC, BibiSebi approved these changes

2023-04-27 08:37 UTC, johannes-lindgren reviewed
Done

2023-04-27 08:44 UTC, eunjae-lee approved these changes

2023-04-27 09:33 UTC, merged