feat(common): rename setValue to setContent
storyblok/field-plugin pull request #177
Opened 2023-05-05 12:32 UTC by eunjae-lee

## What?

As we decided earlier, this PR renames `setValue` to `setContent` which makes more sense.

## Why?

JIRA: EXT-1497

2023-05-05 14:16 UTC, johannes-lindgren requested changes
One small change in the readme. 

We need to update the js template. Since it's not using typescript, it doesn't show an error when you build it...

Otherwise 👍

2023-05-05 14:16 UTC, johannes-lindgren commented on README.md
See line 195

https://github.com/storyblok/field-plugin/pull/177/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L195

2023-05-05 14:16 UTC, johannes-lindgren commented on README.md
> +| `setContent`         | Updates the value of the field plugin. For example, `setContent(3.14159)`
```suggestion
| `setContent`         | Updates the content of the field plugin. For example, `setContent(3.14159)`                                                                                                                               |
```

2023-05-05 14:30 UTC, eunjae-lee commented
@johannes-lindgren I forgot to mention. Yes, I didn't update the JS template yet, because #176 is still open :) I will update it afterwards.

2023-05-09 09:09 UTC, johannes-lindgren approved these changes

2023-05-09 13:11 UTC, merged