feat(helper): add vue 2 submodule
storyblok/field-plugin pull request #231
Opened 2023-07-18 14:10 UTC by eunjae-lee

## What?

This adds `@storyblok/field-plugin/vue2` submodule.

Related:
- https://github.com/storyblok/field-plugin/pull/228
- https://github.com/storyblok/field-plugin/pull/224

## Why?

JIRA: EXT-1828

## How to test? (optional)

2023-07-19 08:20 UTC, eunjae-lee commented
If I run this command,
```
yarn workspace field-plugin-vue2-template build
```

I get this error.

```
"default" is not exported by "../../../../node_modules/vue/dist/vue.runtime.esm-bundler.js", imported by "../../../field-plugin/dist/vue2/index.js".
file: /Users/eunjae/workspace/field-plugin/packages/field-plugin/dist/vue2/index.js:2:7
1: import { createFieldPlugin as g } from "@storyblok/field-plugin";
2: import s from "vue";
          ^
3: function m(n, r, _, p, a, l, d, v) {
4:   var e = typeof n == "function" ? n.options : n;
error during build:
RollupError: "default" is not exported by "../../../../node_modules/vue/dist/vue.runtime.esm-bundler.js", imported by "../../../field-plugin/dist/vue2/index.js".
    at error (file:///Users/eunjae/workspace/field-plugin/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at Module.error (file:///Users/eunjae/workspace/field-plugin/node_modules/rollup/dist/es/shared/node-entry.js:13584:16)
    at Module.traceVariable (file:///Users/eunjae/workspace/field-plugin/node_modules/rollup/dist/es/shared/node-entry.js:14009:29)
    at ModuleScope.findVariable (file:///Users/eunjae/workspace/field-plugin/node_modules/rollup/dist/es/shared/node-entry.js:12527:39)
    at MemberExpression.bind (file:///Users/eunjae/workspace/field-plugin/node_modules/rollup/dist/es/shared/node-entry.js:9462:49)
    at CallExpression.bind (file:///Users/eunjae/workspace/field-plugin/node_modules/rollup/dist/es/shared/node-entry.js:5853:23)
    at CallExpression.bind (file:///Users/eunjae/workspace/field-plugin/node_modules/rollup/dist/es/shared/node-entry.js:9813:15)
    at VariableDeclarator.bind (file:///Users/eunjae/workspace/field-plugin/node_modules/rollup/dist/es/shared/node-entry.js:5853:23)
    at VariableDeclaration.bind (file:///Users/eunjae/workspace/field-plugin/node_modules/rollup/dist/es/shared/node-entry.js:5849:28)
```

When I import the vue 2 helper

```js
import { FieldPluginProvider } from '@storyblok/field-plugin/vue2'
```

this `vue2` submodule has code that imports from vue2, but that's causing this issue, but I'm not sure why, yet.

My theory: when vite imports the submodule, it tries to resolve `vue`, but it's not a dependency of `@storyblok/field-plugin`, so it fails. But... this vue 2 template includes `vue` 🤷🏻‍♂️

One thing I tried is, to copy `helper-vue2/dist/index.js` and bring it directly inside the vue 2 template. It worked. So it's definitely related to how it's importing the library.

WIP

2023-07-24 09:08 UTC, eunjae-lee commented
Current dependencies on/for this PR:
* main
  * **PR #231** <a href="https://app.graphite.dev/github/pr/storyblok/field-plugin/231" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #233** <a href="https://app.graphite.dev/github/pr/storyblok/field-plugin/233" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #234** <a href="https://app.graphite.dev/github/pr/storyblok/field-plugin/234" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/storyblok/field-plugin/231?utm_source=stack-comment).

2023-07-26 09:16 UTC, johannes-lindgren requested changes
This new method (of including field-plugin/react etc)  makes it more complicated to add new templates for new frontend frameworks. Could we describe these added steps in a file, such as `CONTRIBUTING.md`? 

In production, I get the following error: 

> get_html?uid=-preview&protocol=https:&host=app.storyblok.com&preview=1:380 Uncaught ReferenceError: process is not defined

From this line

```js
    productionTip: process.env.NODE_ENV !== 'production',
```

2023-07-27 09:09 UTC, eunjae-lee commented on packages/cli/templates/vue2/src/App.vue
> +.field-plugin-provider {
I thought so, too. But it works! 
https://vuejs.org/api/sfc-css-features.html#child-component-root-elements

2023-08-01 09:01 UTC, johannes-lindgren approved these changes

2023-08-01 09:07 UTC, eunjae-lee commented
@eunjae-lee started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/storyblok/field-plugin/231).

2023-08-01 09:08 UTC, merged

2023-08-01 09:08 UTC, eunjae-lee commented
@eunjae-lee merged this pull request with [Graphite](https://app.graphite.dev/github/pr/storyblok/field-plugin/231).